### ISSUE TITLE
Hide card if no events

### ISSUE THREAD

**Issue by Flintr** [FamousWolf/week-planner-card#109]
I use the card and show 1 day. It would be great to have an option to hide the card if there are no events, instead of showing the “no events” text. I don’t think there’s a straightforward way to create a template sensor that counts events (and pair it with a conditional card), which was my first approach.

**Comment by FamousWolf** [comment]
I haven't tested it, but you can probably already do this with card_mod. Something like this should work:

```css
card_mod:
  style: |
    ha-card:has(.none) {
      display: none !important;
    }
```
