### ISSUE TITLE
Begin first day of the month with month abbreviation. 

### ISSUE THREAD

**Issue by bluk10** [FamousWolf/week-planner-card#113]
I would like the first day of the month to replace "1" with the month abbreviation ex. Sep. Please see image below. Thank you for your work on this amazing card.

![image](https://github.com/user-attachments/assets/db35566d-ffa3-4d43-aa5f-9b2ca7dab9de)

**Comment by FamousWolf** [comment]
I think this is a bit too niche to add an option for it, but it's already possible with card_mod by adding the following configuration:

```css
dayFormat: '''<span data-date="''d''"><span class="number">''d''</span><span class="month">''MMM''</span></span>'''
card_mod:
  style: |
    .container .day .date span .month {
      display: none;
      font-size: var(--day-date-number-font-size);
      line-height: var(--day-date-number-line-height);
    }
    .container .day .date span[data-date="1"] .number {
      display: none;
    }
    .container .day .date span[data-date="1"] .month {
      display: inline;
    }
```

The `dayFormat` option replaces the default date number with `<span data="[current date number]"><span class="number">[current date number</span><span class="month">[current month]</span></span>`. CSS then hides the month span by default and shows it if the current date number is `1`.
