### ISSUE TITLE
card_mod not working

### ISSUE THREAD

**Issue by Byzza** [FamousWolf/week-planner-card#115]
I've tried lots of different options, even starting fresh and just having the basics and I can't seem to get anything working with card_mod.

Any ideas?

HA Version: 2024.8.3
HACS Version: 2.0.0
Week-planner-card Version: 1.6
![image](https://github.com/user-attachments/assets/a12c5543-4ab9-49c4-9da5-43f6138922e4)

**Comment by FamousWolf** [comment]
I can't reproduce this problem. Is card_mod working for other cards?

**Comment by dnoggle** [comment]
I had the same thing happen and clearing the cache fixed it.

**Comment by saryn** [comment]
I also had the same problem. Even clearing cache did not help. So I workarounded it this way:
```yaml
type: custom:mod-card
style:
  week-planner-card$: |
    .today .date {
      background-color: var(--state-active-color)
    }
card:
  type: custom:week-planner-card
  calendars:
    - entity: ...
```
