### ISSUE TITLE
Suggestion - Limit events to display

### ISSUE THREAD

**Issue by Mr-Staffman** [FamousWolf/week-planner-card#129]
Hi and thanks for an awesome card. In my dashboard, I display only family events for the the current day in a small box. It would be nice to be able to set a limit of events to show. If there are more than 3 events on current day, it destroys my design. 

This is not a big issue, I seldom have more than 3 family events for a single day. 

<img width="443" alt="Skärmavbild 2024-09-04 kl  10 51 06" src="https://github.com/user-attachments/assets/5829f708-e25b-4754-a769-0a8b7e65e3e0">

**Comment by FamousWolf** [comment]
I think this is a bit to niche to add an configuration for, but you can already do this with [card-mod](https://github.com/thomasloven/lovelace-card-mod):

```css
card_mod:
  style: |
    .container .events .event:nth-child(n+4) {
      display: none;
    }
```

This will hide all events from the 4th for each day.
