### ISSUE TITLE
Support for tap_action?

### ISSUE THREAD

**Issue by Wetzel402** [FamousWolf/week-planner-card#137]
Does your card support `tap_action`?  If so, how do I get it working?  If not, can this be a feature request?

```
tap_action:
  action: navigate
  navigation_path: /lovelace/calendar
```

I would like a minimal 1 day view to navigate to a 7 day view.

**Comment by FamousWolf** [comment]
This has been added and will be included in the 1.8.0 release.

**Comment by CyberFlexie** [comment]
I can't get this to work. is this the correct syntax? 

```
actions: 
  action: navigate
  navigation_path: /dashboard-tablet/calendar
```

And would something like this be possible?

```
actions: 
  action: url
  url_path: https://calendar.google.com/calendar/u/0/r/month
```

**Comment by FamousWolf** [comment]
@CyberFlexie It should be:

```yaml
actions:
  tap_action:
    action: navigate
    navigation_path: /dashboard-tablet/calendar
```

You're missing the `tap_action:` part.
