### ISSUE TITLE
blank space for hiddendays in panel view

### ISSUE THREAD

**Issue by cofw2005** [FamousWolf/week-planner-card#142]
Hello, in my use case I only want to show the calendar of workdays. I use the card as `type: panel` in a view.
My problem is, when I hide the weekend. Only the events and day header are hidden, the two columns are still there with blank. See below picture:
show 7 days:
![image](https://github.com/user-attachments/assets/ff49e3b1-4f2c-40d5-99fb-cc5fb5479ce7)

show 5 days:
![image](https://github.com/user-attachments/assets/61eb59a6-1d86-4fff-a5a5-e453eb03c752)

Is it possible to automatically tile the shown cards to the full width? the width of a day shall be adjusted depends on the number of shown days instead of a fixed 1/7 width of the card.

Thank you!

**Comment by FamousWolf** [comment]
You can do this using card_mod. Something like this should do it:

```yaml
card_mod:
  style: >
    div.day {
      width: calc((100% - 4 * var(--days-spacing)) / 5) !important;
    }
```
