### ISSUE TITLE
Feature request: force days per row

### ISSUE THREAD

**Issue by sparky-vision** [FamousWolf/week-planner-card#149]
Right now, week-planner-card seems to base the number of days shown on available width. It would be useful to force _n_ days per row, for times when I want it to *always* display, say, exactly one week.

**Comment by tasiotas** [comment]
good idea, for now here is workaround

```css
card_mod:
  style: |
    .container {
      flex-wrap: nowrap !important;
      justify-content: space-around;
    }
```
