### ISSUE TITLE
Feature request: Configurable colour for national holidays and Sundays

### ISSUE THREAD

**Issue by nahvetti** [FamousWolf/week-planner-card#158]
It would be great to have a configurable colour for national holidays and eg. Sundays. Currently it is possible to configure day specific colour with card_mod, but it affects also to event text. I would like to limit this to 'title' of the day (number and day name).

National holidays might be a bit more challenging.. but eg. Google offers and hosts National holiday calendars, maybe events on such calendar entity could trigger the colour change for a day.

**Comment by FamousWolf** [comment]
You can use card_mod to change styling for the `title` of the day, using `div.day.sunday div.date` as a selector. For example:

```yaml
card_mod:
  style: |
    div.day.sunday div.date {
      color: #ff0000;
    }
```

National holidays is indeed more challenging. It's a bit too specific and big for me to add an option for this. However if you show the events from that national holiday calendar you can use card_mod to change the styling of a day that has events from that calendar. For example:

```yaml
card_mod:
  style: |
    div.day:has(div[data-entity="calendar.calendar_holidays"]) div.date {
      color: #ff0000;
    }
```
