### ISSUE TITLE
Configuration with templates possible?

### ISSUE THREAD

**Issue by Ben-Bitdiddle-DE** [FamousWolf/week-planner-card#215]
Hello,

is it possible to make use of template in the configuration. I thought of a possibility the switch the day ahead value (on demand), so i created a number helper for that and wanted it to be used in the configuration:

days: '{{ states("input_select.kalender_anzahltage") }}'

But it seems that this is currently to possible?

KR

**Comment by Kanecaine** [comment]
I would also very much welcome it if it were possible to use templates in the future. This would further expand the possibilities of this great card.

In the meantime, you can make do with a config-template-card, but with a huge disadvantage: the loss of the ability to configure this card via UI.

```yaml
type: custom:config-template-card
entities: 
  - input_select.kalender_anzahltage
variables:
  ANZAHLTAGE: states['input_select.kalender_anzahltage']?.state
card:
  type: custom:week-planner-card
  calendars:
    - entity: calendar.abfallkalender
      name: Müllabholung
      color: orange
  days: "${ ANZAHLTAGE }"
...
```
