### ISSUE TITLE
Feature Request: "Today" visually stand out

### ISSUE THREAD

**Issue by skjeldgaard** [FamousWolf/week-planner-card#216]
Really cool it is!

I like to show 2 weeks, always starting on monday.
I would like to se "Today" somehow viusualy standout in that case. Some color or some border areound the day and events.
Something like:
![download](https://github.com/user-attachments/assets/ce62d65e-caa0-4005-9f1f-3fc8a0a681d5)

Feel free to pick the best option whatever that is :)

Keep up the good work!

**Comment by FamousWolf** [comment]
This can already be done with card-mod. For example:

```yaml
card_mod:
  style: |
    .day.today {
      background-color: #ff0000;
    }
```
