### ISSUE TITLE
Error while fetching Calendar: Response error: 400

### ISSUE THREAD

**Issue by smurf12345** [FamousWolf/week-planner-card#225]
Recently, the card started giving "Error while fetching Calender: Response error: 400" error which as been working up until now.  I'm not sure if a change in home-assistant or week-planner card.  Both are up to date.  It appears to started having issues with a couple calendars in my list.   If I remove them, the card displays the remaining calendars ok.  The problem calendars are all google calendars, 1 put out publicly by the our school and 1 calendar in my google calendar.  As far as I can tell the calendars are accessible via the home-assistant calendar and not seeing errors there.  Any idea where I'm going wrong?

Card config:
```
type: custom:bootstrap-grid-card
class: container-fluid `g-0`
cards:
  - type: row
    class: row
    cards:
      - type: custom:week-planner-card
        compact: false
        class: col-24
        calendars:
          - entity: calendar.abc_planetmurphy_com
            color: "#e6c229"
          - entity: calendar.efg_planetmurphy_com
            color: "#1a8fe3"
          - entity: calendar.kaneland_john_shields_elementary
            color: "#d11149"
          - entity: calendar.district_302
            color: "#d11149"
          - entity: calendar.holidays_in_united_states
            color: "#0099aa"
          - entity: calendar.school
            color: "#000000"
        days: 35
        startingDay: monday
        texts:
          today: ""
          tomorrow: ""
          yesterday: ""
          fullDay: ""
          wednesday: Wed
        weather:
          entity: weather.pirateweather
          showTemperature: true
          showLowTemperature: false
        noCardBackground: false
        eventBackground: rgba(0, 0, 0, .5)
        locationLink: https://www.openstreetmap.org/search?query=
        locale: us
        timeFormat: h:mma
```

Looking at the browser console log it appears to be these calendars with a "fetch-with0-auth" error.

<img width="892" alt="image" src="https://github.com/user-attachments/assets/e428a294-da6d-43d9-a973-caf171b126d0" />

```
import type { Auth } from "home-assistant-js-websocket";

export const fetchWithAuth = async (
  auth: Auth,
  input: RequestInfo,
  init: RequestInit = {}
) => {
  if (auth.expired) {
    await auth.refreshAccessToken();
  }
  init.credentials = "same-origin";
  if (!init.headers) {
    init.headers = {};
  }
  if (!init.headers) {
    init.headers = {};
  }
  // @ts-ignore
  init.headers.authorization = `Bearer ${auth.accessToken}`;
  return fetch(input, init);
};
```
