### ISSUE TITLE
Can't add weather

### ISSUE THREAD

**Issue by bs42** [FamousWolf/week-planner-card#234]
Trying to add weather and I get the following error message in the logs:

```
Logger: frontend.js.modern.202411278
Source: components/system_log/__init__.py:331
First occurred: 9:06:58 AM (3 occurrences)
Last logged: 9:07:01 AM

Uncaught error from Edge 131.0.0.0 on Linux x86_64 TypeError: Cannot add property showCondition, object is not extensible ed.setConfigValue (/hacsfiles/week-planner-card/week-planner-card.js:647:393) ed._valueChanged (/hacsfiles/week-planner-card/week-planner-card.js:647:97) es.handleEvent (/hacsfiles/week-planner-card/week-planner-card.js:10:6019) dispatchEvent (mwc-switch-base.ts:121:13) click (mwc-switch-base.ts:113:23) input.focus (src/components/ha-formfield.ts:45:14) call (src/lit-html.ts:2018:28)
Uncaught error from Edge 131.0.0.0 on Linux x86_64 TypeError: Cannot add property showTemperature, object is not extensible ed.setConfigValue (/hacsfiles/week-planner-card/week-planner-card.js:647:393) ed._valueChanged (/hacsfiles/week-planner-card/week-planner-card.js:647:97) es.handleEvent (/hacsfiles/week-planner-card/week-planner-card.js:10:6019) dispatchEvent (mwc-switch-base.ts:121:13) click (mwc-switch-base.ts:113:23) input.focus (src/components/ha-formfield.ts:45:14) call (src/lit-html.ts:2018:28)
Uncaught error from Edge 131.0.0.0 on Linux x86_64 TypeError: Cannot add property showLowTemperature, object is not extensible ed.setConfigValue (/hacsfiles/week-planner-card/week-planner-card.js:647:393) ed._valueChanged (/hacsfiles/week-planner-card/week-planner-card.js:647:97) es.handleEvent (/hacsfiles/week-planner-card/week-planner-card.js:10:6019) dispatchEvent (mwc-switch-base.ts:121:13) click (mwc-switch-base.ts:113:23) input.focus (src/components/ha-formfield.ts:45:14) call (src/lit-html.ts:2018:28)
```

yaml for the card:
```
type: custom:week-planner-card
calendars:
  - entity: calendar.home_tasks
    color: green
  - entity: calendar.brad
    color: blue
days: "2"
startingDay: today
startingDayOffset: 0
hideWeekend: false
noCardBackground: false
compact: false
locale: en
showLocation: true
hidePastEvents: false
hideDaysWithoutEvents: true
hideTodayWithoutEvents: false
combineSimilarEvents: false
weather:
  entity: weather.jacksonville_weather
```

**Comment by FamousWolf** [comment]
I can not reproduct this, but the yaml for the weather should be:

```yaml
weather:
  - entity: ...
```

You're missing the dash `-`. Perhaps adding that will work.

**Comment by bs42** [comment]
I had used the visual editor to create the yaml, didn't notice the missing dash.  Adding that has suppressed the error, but the frontend isn't showing any weather information.

```
weather:
  - entity: weather.jacksonville_weather
    showCondition: true
    showTemperature: true
```
I also tried with just the entity, with/without the `showCondition` and `showTemperature` options.

My weather entity is supplied by OpenWeatherMap if that is important.

**Comment by SBergers** [comment]
Try adding this:
```
weather:
  showCondition: true
  showTemperature: true
  showLowTemperature: true
  useTwiceDaily: false
  entity: weather.jacksonville_weather
```

its working fine here..
