### ISSUE TITLE
Option to include day name on yesterday, today, tomorrow

### ISSUE THREAD

**Issue by danw87** [FamousWolf/week-planner-card#236]
Hi, great project, please could you include options to include the day names on the yesterday, today, tomorrow days or as space can be tight maybe an option to only show the day name, not today, etc. then the current day is highlighted, like you get in outlook / google calendar

**Comment by FamousWolf** [comment]
You can disable `yesterday`, `today` and `tomorrow` by overriding it:

```yaml
texts:
  yesterday: ""
  today: ""
  tomorrow: ""
```

Highlighting the current day can be done using card-mod. For example:

```yaml
card_mod:
  style: |
    .today .date {
      background-color: #ff0000;
    }
```
