### ISSUE TITLE
Feature request: Custom filtering to event (bold, color, append emoji)

### ISSUE THREAD

**Issue by Adrianni** [FamousWolf/week-planner-card#240]
I would like to request a filter to not only exclude matching events but also apply CSS changes (e.g., color changes, bold text) to highlight the matched events. Additionally it would be great if the filter could add a string (like an emoji) to the event title.

**Comment by FamousWolf** [comment]
You can already do this with card-mod. Every event container div has a data-summery attribute. You can use that in CSS selectors. There's an [example in the documentation](https://github.com/FamousWolf/week-planner-card?tab=readme-ov-file#custom-event-style-based-on-title-text-with-card_mod). You can also use CSS like that to add emoji's. To add a party emoji to events with "Birthday" in the title for example you could do this:

```yaml
card_mod:
  style: |
    .event[data-summary~="Birthday"] .title:after {
      content: '🥳'
    }
```
