### ISSUE TITLE
Feature request: hide card when no events

### ISSUE THREAD

**Issue by martinhoess** [FamousWolf/week-planner-card#249]
when there are no events the card is not completely hidden

**Comment by Sneakybun** [comment]
Add:

            card_mod:
              style: |
                .none {
                  display: none;
                }

this will remove cards without event

**Comment by martinhoess** [comment]
> Add:
> 
> ```
>         card_mod:
>           style: |
>             .none {
>               display: none;
>             }
> ```
> 
> this will remove cards without event

It doesn't work, unfortunately

**Comment by Sneakybun** [comment]
That very unexpected, I had the same issue and found this solution 3 days ago. 

Tried it again in a new dashboard and works for me. 

If you share how you implemented? I can take a look if you like

**Comment by martinhoess** [comment]
the code is the same as in the first post.
I've tried it in a new dashboard, still visible 🤷 

![Image](https://github.com/user-attachments/assets/c5fb23d9-cb0a-4603-98fb-a6f7ef8e9e53)

![Image](https://github.com/user-attachments/assets/ec6608c5-6ce9-40b1-95e4-2859a81f280b)

```
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:week-planner-card
            days: 5
            startingDay: today
            maxEvents: 7
            compact: true
            showLegend: false
            hidePastEvents: true
            hideDaysWithoutEvents: true
            hideTodayWithoutEvents: true
            locale: de
            texts:
              today: Heute
              tomorrow: ''
              yesterday: ''
              fullDay: ' '
            calendars:
              - entity: calendar.office
                name: Büro
                color: '#f09300'
            showLocation: false
            showDescription: false
            columns:
              extraLarge: '1'
              large: '1'
              medium: '1'
              small: '1'
              extraSmall: '1'
            noCardBackground: false
            card_mod:
              style: |
                .none {
                  display: none;
                }
```
