### ISSUE TITLE
add function: Tap function

### ISSUE THREAD

**Issue by Benneboy** [FamousWolf/week-planner-card#279]
currently I am using a rolling 7 day "week" on a home page in one line and would love to be able to tap this to navigate to my full calendar page.

![Image](https://github.com/user-attachments/assets/1504c369-62c7-444c-9cde-d662b146da8e)

at the moment I have had to create a crappy "more" button.

**Comment by FamousWolf** [comment]
This is already possible, just not in the visual editor. You'll have to add it to the yaml configuration. For example:

```yaml
actions:
  tap_action:
    action: navigate
    navigation_path: /lovelace/week-planner-card
```
