### ISSUE TITLE
The weather is not displayed

### ISSUE THREAD

**Issue by 2StrHero** [FamousWolf/week-planner-card#58]
```
weather:
  entity: weather.openweathermap
  showTemperature: true
  showLowTemperature: true
```
```
weather: weather.openweathermap
```
I don't have the weather displayed, and it's loading endlessly. What is the reason for this?
