### ISSUE TITLE
Hide date number

### ISSUE THREAD

**Issue by johannesberg740** [FamousWolf/week-planner-card#61]
It would be great if we could hide the date number. Usecase could be more rows with calendars for family-members to create a family planner with each family member their own row

**Comment by FamousWolf** [comment]
You can use card_mod for that. For example:

```yaml
card_mod:
  style: |
    .day .date .number {
      display: none;
    }
```
