### ISSUE TITLE
Event background color

### ISSUE THREAD

**Issue by B3voholic** [FamousWolf/week-planner-card#63]
It would be really nice if you could style the entire event a certain color instead of just having a bar on the left.

**Comment by FamousWolf** [comment]
The calendar color is set using a CSS variable `--border-color`, so you can use that with card_mod to set it to the background.

This should do it:

```yaml
card_mod:
  style: |
    .event {
      background-color: var(--border-color) !important;
    }
```
