### ISSUE TITLE
Showing Today for 1 day excludes entries after midnight GMT

### ISSUE THREAD

**Issue by cmause** [FamousWolf/week-planner-card#77]
When displaying just today on a dashboard, only items from midnight local through 5:00 p.m. local are displayed.  My time zone is GMT -700, so the cutoff corresponds to midnight GMT.

```
type: custom:week-planner-card
calendars:
  - entity: calendar.chris
    color: '#1976d2'
timeFormat: t
days: 1
startingDay: today
```

If I start playing with the days parameter, setting it to 1.2, for example, the full day will be displayed, but it will also display Tomorrow, with no events.

Desired behavior:  Displaying Today for 1 day should cover all events from midnight to midnight local time.
Additional adjustment:  Use only integer portion of Days parameter
