### ISSUE TITLE
"hideDaysWithoutEvents" conflicts with "days" option

### ISSUE THREAD

**Issue by Emeraude998** [FamousWolf/week-planner-card#79]
# Description
Hello, I'm having trouble with displaying a certain number of days while also hiding/ignoring the days without any events.
Here is my config:
```
type: custom:week-planner-card
calendars:
  - entity: calendar.famille
    color: blue
days: 5
noCardBackground: true
hideDaysWithoutEvents: true
hidePastEvents: true
showLocation: true
compact: true
```
# What is expected to happen:
Shows the next 5 days with events and hides the days without any event till 5 days are shown.
# What actually happens:
Shows the days with events in the next 5 days and hides the one without any events, resulting in only 2 or 3 days showing.

Is there an option I'm not aware of that would fix this issue?
